name: Update labels

on:
  push:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
      - name: Install dependencies
        run: python -m pip install --upgrade pip -r requirements.txt
      - name: Update analysis notebook
        run: |
          python -m pip install jupyter nbconvert nbformat
          jupyter nbconvert --to notebook --execute label_genearator/label_generator.ipynb --ExecutePreprocessor.kernel_name='python3' --output ../notebook_executed
      - name: commit updated notebook
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Commit
          message: "Add pdf"
          add: "label_genearator/pdf_out"
